eureka:
  instance:
    preferIpAddress: true
logging:
  level:
    root: INFO
    feign: INFO
feign:
  client:
    config:
      default:
        logger-level: full

---
spring:
  profiles: docker
eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://discovery-service:8761/eureka/