server:
  port: ${SERVER_PORT:8082}
  servlet:
    context-path: ${SERVER_CONTEXT_PATH:}

eureka:
  client:
    register-with-eureka: true
    fetch-registry: false

spring:
  elasticsearch:
    rest:
      uris: ${ELASTIC_REST:localhost:9200}
  data.elasticsearch:
    cluster-name: ${ELASTIC_CLUSTER:elasticsearch}
    cluster-nodes: ${ELASTIC_NODES:localhost:9300}