config-service:
  image:  dms/config-service
  hostname: config-service
  ports:
    - "8100:8100"
  volumes:
    - ./config-service/config:/app/config
discovery-service:
  image:  dms/discovery-service
  ports:
    - "8761:8761"
  links:
    - "config-service"

#config-service:
#  image:  dms/config-service
#  hostname: config-service
#  ports:
#    - "8100:8100"
#  volumes:
#    - ./config-service/config:/app/config
#discovery-service:
#  image:  dms/discovery-service
#  ports:
#    - "8761:8761"
#  links:
#    - "config-service"
#
#gateway-service:
#  image:  dms/gateway-service
#  ports:
#    - "8762:8762"
#  links:
#    - "config-service"
#    - "discovery-service"

#service-b:
#  image:  spring-cloud-netflix-example/service-b
#  links:
#    - "eureka-server"
#    - "config-server"
#    - "hystrix-dashboard"
#    - "rabbitmq"
#    - "zipkin"
#
#service-a:
#  image:  spring-cloud-netflix-example/service-a
#  links:
#    - "eureka-server"
#    - "config-server"
#    - "service-b"
#    - "hystrix-dashboard"
#    - "rabbitmq"
#    - "zipkin"
#
#admin-dashboard:
#  image:  spring-cloud-netflix-example/admin-dashboard
#  ports:
#    - "8040:8040"
#  links:
#    - "eureka-server"
#    - "rabbitmq"
#    - "config-server"
#    - "service-a"
#    - "service-b"
#    - "zuul"
#    - "hystrix-dashboard"
#
#zuul:
#  image:  spring-cloud-netflix-example/zuul
#  ports:
#    - "8060:8060"
#  links:
#    - "eureka-server"
#    - "config-server"
#    - "service-a"
#    - "rabbitmq"
#    - "zipkin"
#
#hystrix-dashboard:
#  image:  spring-cloud-netflix-example/hystrix-dashboard
#  ports:
#    - "8050:8050"
#  links:
#    - "eureka-server"