server.port: 8200
oauth-client:
  client-id: JMMDd2sBsImTnfXc1P9t
  secret: af1778ba-8b89-448c-b942-f44422b70dbe
  grant-type: client_credentials
  access-token-endpoint: http://localhost:8090/oauth/token
  log-endpoint: http://localhost:8090/device-log
states:
  enabled:
    param1: 100
    param2: 200
    param3: 35
    status: UP
  disabled:
    param1: 10
    param2: 20
    param3: 5
    status: DOWN