spring:
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: file:./config-service/src/main/resources/configuration

server:
  port: 8888

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true